---
name: Container Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 1 * * 0"

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2.2.0
    - uses: docker/setup-buildx-action@v2.7.0

    - name: Login to DockerHub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./
        file: Containerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: ${{ github.repository }}:latest
        
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3.4.1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        short-description: OCI Image for Proxmox Backup Client 
